# Generated by Django 3.1.2 on 2020-10-18 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
