# Generated by Django 3.1.2 on 2020-11-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201030_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='needs_license',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='needs_medical_certificate',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='water_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='wetsuit_allowed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='app.organizer'),
        ),
    ]
