# Generated by Django 3.1.2 on 2020-11-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201126_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='wetsuit_allowed',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='event',
            name='water_type',
            field=models.CharField(choices=[('river', 'river'), ('sea', 'sea'), ('lake', 'lake')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='wetsuit',
            field=models.CharField(choices=[('compulsory', 'compulsory'), ('optional', 'optional'), ('prohibited', 'prohibited')], max_length=10, null=True),
        ),
    ]
