# Generated by Django 3.1.2 on 2020-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201129_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='verified_at',
            field=models.DateField(blank=True, help_text='set if the event has been verified by the admin', null=True),
        ),
    ]
