# Generated by Django 3.1.2 on 2020-12-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='set if the event has been verified by the admin', null=True),
        ),
    ]
