# Generated by Django 3.1.2 on 2020-12-06 08:24

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201206_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
