# Generated by Django 3.1.2 on 2020-12-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201206_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='street',
        ),
        migrations.AlterField(
            model_name='event',
            name='water_type',
            field=models.CharField(blank=True, choices=[('river', 'River'), ('sea', 'Sea'), ('lake', 'Lake'), ('pool', 'Pool')], max_length=10, null=True),
        ),
    ]
