# Generated by Django 3.1.2 on 2020-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201206_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_quality',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], max_length=10, null=True),
        ),
    ]
