# Generated by Django 3.1.2 on 2020-12-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_event_entry_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sold_out',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
