# Generated by Django 3.1.2 on 2020-12-13 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20201213_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='edited_by',
            field=models.ForeignKey(help_text='Author who has done the laste edit', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
