# Generated by Django 3.1.2 on 2020-12-13 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_auto_20201213_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='internal_comment',
            field=models.TextField(blank=True, default='', help_text='Comment not shown to the public', max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='edited_at',
            field=models.DateTimeField(help_text='Timestamp of the last edit', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='edited_by',
            field=models.ForeignKey(help_text='Author who has done the last edit', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateTimeField(help_text='Date time of event, in local time'),
        ),
    ]
