# Generated by Django 3.1.2 on 2020-12-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201213_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_time',
            field=models.TimeField(blank=True, default=None, help_text='Date and time of event, in local time', null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(help_text='Date of event, in local time'),
        ),
    ]
