# Generated by Django 3.1.2 on 2020-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201213_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='header_photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Comment shown to the public', max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='internal_comment',
            field=models.TextField(blank=True, default='', help_text='Comment NOT shown to the public', max_length=1024),
        ),
    ]
