# Generated by Django 3.1.2 on 2020-12-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201219_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='with_ranking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Comment shown to the public', max_length=2048),
        ),
        migrations.AlterField(
            model_name='event',
            name='internal_comment',
            field=models.TextField(blank=True, default='', help_text='Comment NOT shown to the public', max_length=2048),
        ),
        migrations.AlterField(
            model_name='location',
            name='header_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
