# Generated by Django 3.1.2 on 2020-12-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201223_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invisible',
            field=models.BooleanField(blank=True, default=False, help_text='Hidden from public', null=True),
        ),
    ]
