# Generated by Django 3.1.2 on 2020-12-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_event_invisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flyer_image',
            field=models.ImageField(blank=True, help_text='Flyer or poster showing event details', null=True, upload_to='flyers'),
        ),
    ]
