# Generated by Django 3.1.2 on 2021-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_event_flyer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='water_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='water_type',
            field=models.CharField(blank=True, choices=[('river', 'River'), ('sea', 'Sea'), ('lake', 'Lake'), ('pool', 'Pool')], max_length=10, null=True),
        ),
    ]
