# Generated by Django 3.1.2 on 2021-01-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210104_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='water_type',
        ),
    ]
