# Generated by Django 3.1.2 on 2021-01-10 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_event_water_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), blank=True, help_text='Coordinates (lat/lng) of track', null=True, size=None),
        ),
    ]
