# Generated by Django 3.1.2 on 2021-01-17 09:16

from django.db import migrations
from django.utils.text import slugify

from app.models import Event


def forwards(apps, schema_editor):
    """
    Add Slugs for each event
    :param apps:
    :param schema_editor:
    :return:
    """
    for event in Event.objects.all():
        slug_source = event.name + " " + event.location.city + " " + str(event.date_start)
        event.slug = slugify(slug_source[0:100])
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0028_event_slug'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
