# Generated by Django 3.1.2 on 2021-01-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210117_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_logo'),
        ),
    ]
