# Generated by Django 3.1.2 on 2021-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_organizer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
