# Generated by Django 3.1.6 on 2021-02-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_organizer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['date', 'race_time', 'distance']},
        ),
    ]
