# Generated by Django 3.1.6 on 2021-02-07 16:01

from django.db import migrations
from django.template.defaultfilters import slugify

from app.models import Organizer


def forwards(apps, schema_editor):
    """
    Add Slugs for each organizer
    :param apps:
    :param schema_editor:
    :return:
    """
    for organizer in Organizer.objects.all():
        slug_source = organizer.name
        if not organizer.slug:
            organizer.slug = slugify(slug_source[0:100])
            organizer.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0028_event_slug'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0032_auto_20210204_0737'),
    ]

    operations = [
    ]
