# Generated by Django 3.1.6 on 2021-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210207_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='internal_comment',
            field=models.TextField(blank=True, default='', help_text='Comment NOT shown to the public', max_length=10000),
        ),
        migrations.AlterField(
            model_name='event',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last edit', null=True),
        ),
    ]
