# Generated by Django 3.1.6 on 2021-04-03 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_auto_20210213_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(help_text='Author who has created the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='edited_by',
            field=models.ForeignKey(help_text='Author who has done the last edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
