# Generated by Django 3.1.6 on 2021-06-25 19:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210618_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of origin of author', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
