# Generated by Django 3.1.6 on 2021-06-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210625_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='average_rating',
            field=models.FloatField(blank=True, help_text='Stores the average rating of all events happened here', null=True),
        ),
    ]
