# Generated by Django 3.2.9 on 2021-11-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_location_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='previous_year_event',
            field=models.ForeignKey(help_text='Link to the event of the previous year', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
    ]
