# Generated by Django 3.2.25 on 2025-03-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_add_verified_at_to_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
