# Generated by Django 3.2.25 on 2025-04-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_auto_20250317_2127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
