# Generated by Django 3.2.25 on 2025-04-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_auto_20250412_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organizer",
            name="contact_form_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizer",
            name="contact_notes",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="organizer",
            name="contact_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("contacted", "Contacted"),
                    ("responded", "Responded"),
                    ("completed", "Completed"),
                    ("failed", "Failed to Contact"),
                    ("needs_review", "Needs Review"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizer",
            name="last_contact_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
