# Generated by Django 3.2.25 on 2025-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_add_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active_user_count',
            field=models.IntegerField(blank=True, help_text="Number of active users from Google Analytics for this event's page", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='active_user_count_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time active_user_count was updated from Google Analytics', null=True),
        ),
    ]
