# Generated by Django 3.2.25 on 2025-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_add_event_analytics_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='marketing_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time a marketing email was sent to this organizer', null=True),
        ),
    ]
