# Generated by Django 3.2.25 on 2025-12-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_add_organizer_marketing_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='language',
            field=models.CharField(blank=True, help_text="ISO language code (e.g., 'en', 'de', 'fr'). Auto-detected if empty.", max_length=5, null=True),
        ),
    ]
