# Generated by Django 3.2.25 on 2025-12-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_add_language_to_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('homepage_url', models.URLField(max_length=500)),
                ('last_crawled_at', models.DateTimeField(blank=True, help_text='Last time this source was crawled for updates', null=True)),
                ('crawl_profile', models.CharField(blank=True, help_text='Optional crawl profile ID for custom scraping logic', max_length=100)),
                ('internal_comment', models.TextField(blank=True, default='', help_text='Internal notes about this crawl source', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_sources', to='app.organizer')),
            ],
            options={
                'verbose_name': 'Crawl Source',
                'verbose_name_plural': 'Crawl Sources',
                'ordering': ['name'],
                'unique_together': {('homepage_url', 'organizer')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='crawl_source',
            field=models.ForeignKey(blank=True, help_text='If set, this event will be updated via batch crawling of the source homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='app.crawlsource'),
        ),
    ]
