# Generated by Django 3.2.25 on 2025-12-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_add_crawl_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlsource',
            name='source_type',
            field=models.CharField(choices=[('series', 'Event Series'), ('calendar', 'Event Calendar')], default='series', help_text='series: events matched by date order; calendar: events processed independently', max_length=20),
        ),
        migrations.AlterField(
            model_name='crawlsource',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Required for series type; optional for calendar type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_sources', to='app.organizer'),
        ),
    ]
