# Generated by Django 3.2.25 on 2025-12-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_organizer_claim_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by_organizer',
            field=models.ForeignKey(blank=True, help_text='Organizer who created this location (for organizer portal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to='app.organizer'),
        ),
    ]
