# Generated by Django 3.2.25 on 2026-02-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_increase_location_field_lengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='marketing_email_sent_at',
        ),
    ]
